In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('winequality-red.csv')
df.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  
0      9.4        5  
1      9.8        5  
2      9.8        5  
3      9.8        6  
4      9.4        5

In [3]:
df.shape

(1599, 12)

In [4]:
df.isnull().sum()

fixed acidity           0
volatile acidity        0
citric acid             0
residual sugar          0
chlorides               0
free sulfur dioxide     0
total sulfur dioxide    0
density                 0
pH                      0
sulphates               0
alcohol                 0
quality                 0
dtype: int64

In [5]:
df['quality'].value_counts()

5    681
6    638
7    199
4     53
8     18
3     10
Name: quality, dtype: int64

In [6]:
df.dtypes

fixed acidity           float64
volatile acidity        float64
citric acid             float64
residual sugar          float64
chlorides               float64
free sulfur dioxide     float64
total sulfur dioxide    float64
density                 float64
pH                      float64
sulphates               float64
alcohol                 float64
quality                   int64
dtype: object

In [7]:
x = df.iloc[:,:-1]
y = df.iloc[:,-1]
print(x.shape)
print(y.shape)
print(type(x))
print(type(y))

(1599, 11)
(1599,)
<class 'pandas.core.frame.DataFrame'>
<class 'pandas.core.series.Series'>


In [8]:
x.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  
0      9.4  
1      9.8  
2      9.8  
3      9.8  
4      9.4

In [9]:
y.head()

0    5
1    5
2    5
3    6
4    5
Name: quality, dtype: int64

In [10]:
from sklearn.model_selection import train_test_split

In [11]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.30)
print(x_train.shape)
print(x_test.shape)
print(y_train.shape)
print(y_test.shape)

(1119, 11)
(480, 11)
(1119,)
(480,)


In [12]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

In [13]:
def gen_metrics(ytest,ypred):                                     
    cm = confusion_matrix(ytest,ypred)
    print('Confusion Matrix\n',cm)
    print('Classfication Report\n',classification_report(ytest,ypred,zero_division=0))
    
def tt_score(model):                                              
    print('Training Score',model.score(x_train,y_train))
    print('Testing Score',model.score(x_test,y_test))

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
m1 = LogisticRegression(max_iter=1000,solver='liblinear')
m1.fit(x_train,y_train)

LogisticRegression(max_iter=1000, solver='liblinear')

In [16]:
tt_score(m1)

Training Score 0.5817694369973191
Testing Score 0.6


In [17]:
ypred_m1 = m1.predict(x_test)
print(ypred_m1)

[6 6 5 5 6 5 6 5 6 5 6 6 6 6 5 5 6 6 5 5 5 5 6 5 6 6 5 6 7 6 7 5 5 6 6 6 5
 6 6 6 6 6 5 5 5 5 5 6 6 6 5 5 5 5 6 6 6 6 5 5 5 5 6 5 5 6 5 5 7 6 5 5 5 6
 5 5 5 5 5 6 6 5 6 5 7 5 6 5 7 6 5 7 7 6 5 6 6 6 7 5 5 5 5 7 6 6 6 7 5 6 5
 5 6 6 6 5 6 5 5 5 6 6 6 5 6 5 6 6 5 5 5 5 5 5 6 5 5 6 6 6 5 6 6 6 6 5 5 5
 5 6 6 5 6 5 6 6 6 6 5 6 6 5 6 5 5 6 5 5 6 5 6 6 6 5 5 5 5 6 5 6 6 6 6 5 7
 6 6 6 6 5 5 5 6 5 5 5 5 6 5 5 6 6 6 5 5 5 6 5 7 6 5 5 6 5 5 6 6 5 6 6 6 5
 5 5 5 6 5 5 5 6 6 5 6 5 6 5 5 5 5 5 6 6 5 6 5 6 5 5 5 5 5 6 5 6 5 5 5 5 6
 6 5 6 5 5 6 5 5 6 6 5 5 6 5 5 5 6 6 6 5 5 6 7 5 5 6 5 5 5 6 5 6 6 5 6 5 5
 6 5 5 5 5 6 6 6 6 5 5 6 5 5 5 6 5 5 5 7 6 5 6 6 6 5 7 5 7 5 5 5 6 6 7 6 5
 6 5 6 6 5 5 6 5 6 5 5 5 5 7 6 6 5 5 5 6 6 6 5 5 5 6 5 6 5 5 6 6 5 6 6 6 5
 5 5 6 5 6 6 6 6 5 6 5 5 5 6 6 5 5 5 5 6 5 7 5 6 6 5 5 6 6 6 5 5 6 6 5 6 5
 5 7 5 5 6 6 6 6 5 5 6 5 5 5 5 5 5 6 6 6 5 6 6 6 5 5 6 5 6 6 5 6 6 6 6 5 5
 6 5 6 6 5 5 6 5 5 6 6 6 5 5 5 6 5 7 6 5 6 5 5 5 5 6 6 5 7 5 7 5 5 5 5 5]


In [18]:
gen_metrics(y_test,ypred_m1)

Confusion Matrix
 [[  0   0   3   1   0   0]
 [  0   0   8   4   1   0]
 [  0   0 153  33   3   0]
 [  0   0  78 125   8   0]
 [  0   0   7  40  10   0]
 [  0   0   0   5   1   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        13
           5       0.61      0.81      0.70       189
           6       0.60      0.59      0.60       211
           7       0.43      0.18      0.25        57
           8       0.00      0.00      0.00         6

    accuracy                           0.60       480
   macro avg       0.28      0.26      0.26       480
weighted avg       0.56      0.60      0.57       480



In [19]:
from sklearn.tree import DecisionTreeClassifier

In [20]:
m2 = DecisionTreeClassifier(criterion='entropy',max_depth=15)
m2.fit(x_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=15)

In [21]:
tt_score(m2)

Training Score 0.9991063449508489
Testing Score 0.5916666666666667


In [22]:
ypred_m2 = m2.predict(x_test)
print(ypred_m2)

[7 6 5 6 6 6 6 5 7 5 7 6 7 6 5 6 6 7 5 6 5 5 7 5 6 7 5 6 7 5 6 4 5 7 5 4 5
 5 7 5 6 6 5 5 5 4 4 6 6 5 6 5 5 5 5 8 5 7 6 5 5 5 6 5 7 6 5 5 7 5 6 5 5 5
 5 5 6 6 6 6 6 6 6 5 6 6 7 4 6 7 5 7 7 6 5 5 7 6 8 5 7 5 5 6 7 6 6 7 6 6 6
 5 6 7 6 5 7 5 5 5 7 5 6 5 6 6 6 5 5 5 6 8 5 5 7 5 4 6 7 5 5 7 6 7 6 5 6 5
 5 6 5 5 7 5 7 5 6 6 5 6 7 6 6 6 6 6 5 5 6 6 6 7 6 5 5 6 5 7 5 5 7 6 6 6 6
 6 6 6 6 5 5 5 7 5 5 5 5 5 5 5 6 6 6 4 5 5 6 5 6 6 6 7 6 5 5 6 6 5 6 5 7 5
 8 5 5 6 6 6 5 6 5 5 7 5 4 5 5 5 5 6 6 6 5 6 6 7 6 6 5 5 4 6 5 6 5 5 5 5 6
 6 5 5 6 6 5 5 5 6 7 5 6 7 5 5 6 7 7 6 5 5 5 5 5 5 5 6 5 6 5 6 5 5 5 7 6 5
 6 6 4 6 5 6 6 6 6 5 4 6 6 6 5 5 5 4 6 7 7 6 5 5 6 5 7 5 6 5 5 5 6 6 5 6 5
 6 5 5 6 5 5 6 5 5 5 6 6 5 6 6 6 5 5 5 6 5 6 5 6 5 6 4 4 5 5 7 7 5 7 5 5 7
 5 5 6 5 6 6 6 6 3 6 5 5 5 6 7 5 5 6 5 6 5 7 5 7 6 6 5 7 7 6 5 6 6 6 5 4 5
 5 7 5 5 5 6 7 7 5 5 6 4 5 5 4 5 4 6 6 6 6 7 7 7 5 5 6 5 6 6 5 7 6 7 7 6 6
 7 5 8 5 5 5 6 5 5 4 7 5 6 4 5 6 5 8 6 6 6 5 5 6 4 4 6 5 8 6 6 5 5 6 5 5]


In [23]:
gen_metrics(y_test,ypred_m2)

Confusion Matrix
 [[  0   3   1   0   0   0]
 [  0   2   3   5   3   0]
 [  1   9 137  37   5   0]
 [  0   6  63 111  25   6]
 [  0   2   2  20  33   0]
 [  0   0   1   3   1   1]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.09      0.15      0.11        13
           5       0.66      0.72      0.69       189
           6       0.63      0.53      0.57       211
           7       0.49      0.58      0.53        57
           8       0.14      0.17      0.15         6

    accuracy                           0.59       480
   macro avg       0.34      0.36      0.34       480
weighted avg       0.60      0.59      0.59       480



In [24]:
from sklearn.neighbors import KNeighborsClassifier

In [25]:
m3 = KNeighborsClassifier(n_neighbors=17)
m3.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=17)

In [26]:
tt_score(m3)

Training Score 0.5701519213583557
Testing Score 0.5145833333333333


In [27]:
ypred_m3 = m3.predict(x_test)
print(ypred_m3)

[6 6 5 5 5 6 6 5 6 6 6 7 5 5 6 5 5 5 5 5 5 5 5 5 6 6 5 5 5 6 5 5 5 6 6 5 5
 5 5 5 5 6 6 5 5 5 6 6 6 5 5 5 5 5 5 5 5 5 5 5 6 5 6 5 5 5 6 6 6 6 5 5 5 6
 5 5 6 5 5 5 6 6 5 5 5 6 6 5 7 6 5 6 7 6 5 6 6 5 6 6 5 6 5 5 6 7 5 5 5 6 5
 5 5 5 6 6 5 5 5 5 6 5 6 5 6 5 6 5 5 5 6 5 5 5 6 5 5 5 6 6 5 6 7 6 6 5 6 5
 5 5 6 6 5 5 7 6 6 5 5 6 6 5 6 6 5 6 5 5 5 5 5 6 6 5 5 6 5 5 5 6 6 6 6 5 6
 5 6 5 5 5 5 5 5 5 5 5 5 5 5 6 6 5 6 5 5 5 5 5 6 7 6 5 6 6 5 6 5 5 6 5 6 5
 6 5 5 6 5 6 5 5 6 6 6 6 5 5 5 6 5 5 5 7 5 6 6 6 5 6 5 5 5 5 5 6 5 5 5 5 6
 5 5 6 5 6 6 6 6 5 6 5 5 5 5 5 5 5 5 6 5 5 5 7 5 6 6 5 5 5 5 5 6 5 5 5 5 5
 6 5 5 6 6 6 6 6 6 5 6 6 5 5 5 6 5 6 5 7 5 5 5 5 6 5 6 5 7 5 6 5 6 6 6 6 5
 7 5 6 5 5 5 6 6 5 6 5 5 5 7 6 6 5 5 6 5 5 5 5 5 6 6 5 6 5 5 5 5 6 6 6 5 5
 6 6 6 5 6 6 6 6 5 5 5 5 5 6 5 5 5 5 6 6 5 6 5 6 5 6 5 6 5 5 5 5 5 5 5 7 5
 5 6 5 5 6 5 5 6 5 6 6 5 5 6 5 5 6 6 5 5 5 6 5 5 5 5 5 5 6 6 5 5 6 5 5 6 6
 6 5 6 5 5 5 6 5 6 6 6 5 5 6 5 5 5 6 6 5 5 5 5 5 5 5 6 5 6 5 5 6 6 5 5 5]


In [28]:
gen_metrics(y_test,ypred_m3)

Confusion Matrix
 [[  0   0   3   1   0   0]
 [  0   0   4   9   0   0]
 [  0   0 149  39   1   0]
 [  0   0 112  92   7   0]
 [  0   0  17  34   6   0]
 [  0   0   3   3   0   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        13
           5       0.52      0.79      0.62       189
           6       0.52      0.44      0.47       211
           7       0.43      0.11      0.17        57
           8       0.00      0.00      0.00         6

    accuracy                           0.51       480
   macro avg       0.24      0.22      0.21       480
weighted avg       0.48      0.51      0.47       480



In [29]:
from sklearn.svm import SVC

In [30]:
m4 = SVC(kernel='poly',C=100,degree=4)
m4.fit(x_train,y_train)

SVC(C=100, degree=4, kernel='poly')

In [31]:
tt_score(m4)

Training Score 0.5227882037533512
Testing Score 0.5395833333333333


In [32]:
ypred_m4 = m4.predict(x_test)
print(ypred_m4)

[6 6 5 5 6 6 6 5 6 5 6 6 6 6 6 6 6 6 5 6 5 6 6 6 6 6 5 6 7 6 6 6 6 6 6 6 6
 6 6 6 6 6 6 5 5 6 6 6 6 6 5 5 5 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 5 6 6
 5 6 5 6 5 6 6 6 7 5 5 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 5 5 6 6 6 6 5 6 6 6 5
 6 6 6 6 6 6 6 5 6 6 6 6 5 6 6 6 6 5 6 6 6 6 5 6 5 6 6 6 6 5 6 6 6 6 5 6 5
 6 6 6 6 6 5 6 6 6 6 6 6 6 5 5 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 6
 6 6 6 6 5 5 5 6 5 6 6 5 6 6 6 6 6 6 5 5 6 5 6 6 6 6 6 6 6 5 6 6 5 6 6 6 5
 6 5 6 6 7 6 5 6 6 6 6 5 6 5 5 6 6 6 6 6 5 6 5 6 6 6 6 5 6 6 5 6 5 5 5 5 6
 6 6 6 5 6 6 6 6 6 6 5 5 6 5 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6 5 6 6 5 6 5 5
 6 5 6 6 5 6 6 6 6 5 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 5 6 5 6 5 6 5 6 6 6 6 5
 6 6 6 6 5 5 6 6 7 6 6 5 5 6 6 6 5 5 6 6 6 6 5 6 6 6 5 6 5 5 6 6 6 6 6 6 6
 6 6 6 5 6 6 6 6 5 6 6 6 5 6 6 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 5
 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 5 6 6 6 6 6 5 6 6 6 6 6 5
 6 6 6 6 6 5 6 5 6 6 6 6 6 6 5 6 5 6 6 5 6 5 5 6 6 6 6 5 6 6 6 6 6 5 5 6]


In [33]:
gen_metrics(y_test,ypred_m4)

Confusion Matrix
 [[  0   0   0   4   0   0]
 [  0   0   4   9   0   0]
 [  0   0  76 110   3   0]
 [  0   0  27 183   1   0]
 [  0   0   2  55   0   0]
 [  0   0   0   6   0   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        13
           5       0.70      0.40      0.51       189
           6       0.50      0.87      0.63       211
           7       0.00      0.00      0.00        57
           8       0.00      0.00      0.00         6

    accuracy                           0.54       480
   macro avg       0.20      0.21      0.19       480
weighted avg       0.49      0.54      0.48       480



In [34]:
from sklearn.ensemble import RandomForestClassifier

In [35]:
m5 = RandomForestClassifier(n_estimators=80,criterion='gini',max_depth=9)
m5.fit(x_train,y_train)

RandomForestClassifier(max_depth=9, n_estimators=80)

In [36]:
tt_score(m5)

Training Score 0.9294012511170688
Testing Score 0.6666666666666666


In [37]:
ypred_m5 = m5.predict(x_test)
print(ypred_m5)

[7 6 5 5 6 6 5 5 6 5 6 7 7 6 5 5 6 6 5 5 5 5 6 5 6 7 5 6 7 5 6 5 5 5 6 5 5
 6 7 7 6 5 5 5 5 5 5 6 6 6 5 5 5 5 6 6 6 6 6 5 6 5 6 5 5 6 5 5 7 6 5 5 6 5
 6 5 5 6 5 6 6 5 5 5 6 5 6 5 7 7 5 7 7 6 5 6 7 6 7 5 6 5 5 6 7 6 5 7 5 6 5
 5 6 6 6 5 7 5 5 5 6 6 6 5 6 5 6 6 5 5 5 5 5 5 6 5 5 6 7 6 5 7 6 6 6 5 5 5
 5 6 5 5 6 5 6 5 6 6 5 6 6 5 6 5 5 6 6 6 5 5 6 6 6 5 5 6 5 6 6 6 6 6 6 5 6
 6 5 5 6 5 5 5 7 5 6 6 5 5 5 5 6 6 7 5 5 5 5 5 7 6 6 7 7 5 5 6 6 5 6 6 6 5
 6 6 5 6 6 6 5 6 5 5 7 5 6 5 5 6 5 5 5 7 5 6 5 6 6 6 5 5 4 6 5 5 6 5 5 5 6
 6 5 6 5 6 5 5 6 7 7 5 5 7 5 5 5 6 7 6 5 5 6 7 5 5 5 5 5 5 5 5 5 6 5 7 6 5
 6 5 5 6 5 6 6 6 6 5 6 6 6 6 5 6 6 5 5 7 5 6 5 5 6 5 7 5 6 5 5 5 6 6 5 6 5
 6 5 6 6 5 5 6 5 5 5 6 5 5 7 6 6 5 5 5 5 5 6 5 5 5 6 6 6 5 5 7 6 5 7 5 5 6
 5 6 6 5 6 6 6 6 5 6 5 5 5 6 6 5 5 6 5 6 5 7 6 6 6 5 6 7 7 6 5 5 6 6 5 7 5
 5 7 6 5 6 6 7 7 5 5 6 6 5 5 5 5 5 5 7 6 6 7 6 7 5 5 6 5 6 6 5 6 6 6 6 6 5
 7 5 7 5 5 5 6 5 5 6 7 5 5 5 5 5 5 6 7 5 6 5 5 5 6 6 6 5 7 6 6 6 5 5 5 5]


In [38]:
from collections import Counter
c1 = Counter(ypred_m5)
print(c1)

Counter({5: 237, 6: 190, 7: 52, 4: 1})


In [39]:
gen_metrics(y_test,ypred_m5)

Confusion Matrix
 [[  0   1   2   1   0   0]
 [  0   0   6   7   0   0]
 [  0   0 160  28   1   0]
 [  0   0  63 129  19   0]
 [  0   0   6  20  31   0]
 [  0   0   0   5   1   0]]
Classfication Report
               precision    recall  f1-score   support

           3       0.00      0.00      0.00         4
           4       0.00      0.00      0.00        13
           5       0.68      0.85      0.75       189
           6       0.68      0.61      0.64       211
           7       0.60      0.54      0.57        57
           8       0.00      0.00      0.00         6

    accuracy                           0.67       480
   macro avg       0.33      0.33      0.33       480
weighted avg       0.64      0.67      0.65       480



In [44]:
 def model_perf(model, x_train,x_test,y_test, y_train):
    model.fit(x_train,y_train)
    ypred = model.predict(x_test)
    print(ypred)
    cm = confusion_matrix(y_test,ypred)
    print('confusion matrix\n',cm)
    print('Classification report\n',classification_report(y_test,ypred,zero_division=0))
    print('Acc score',accuracy_score(y_test,ypred))
    
    print('Training score',model.score(x_train,y_train))
    print('Testing score',model.score(x_test,y_test))

In [45]:
w1 = LogisticRegression(max_iter=1000,solver='liblinear')
model_perf(w1, x_train,x_test,y_test, y_train)

[6 6 5 5 6 5 6 5 6 5 6 6 6 6 5 5 6 6 5 5 5 5 6 5 6 6 5 6 7 6 7 5 5 6 6 6 5
 6 6 6 6 6 5 5 5 5 5 6 6 6 5 5 5 5 6 6 6 6 5 5 5 5 6 5 5 6 5 5 7 6 5 5 5 6
 5 5 5 5 5 6 6 5 6 5 7 5 6 5 7 6 5 7 7 6 5 6 6 6 7 5 5 5 5 7 6 6 6 7 5 6 5
 5 6 6 6 5 6 5 5 5 6 6 6 5 6 5 6 6 5 5 5 5 5 5 6 5 5 6 6 6 5 6 6 6 6 5 5 5
 5 6 6 5 6 5 6 6 6 6 5 6 6 5 6 5 5 6 5 5 6 5 6 6 6 5 5 5 5 6 5 6 6 6 6 5 7
 6 6 6 6 5 5 5 6 5 5 5 5 6 5 5 6 6 6 5 5 5 6 5 7 6 5 5 6 5 5 6 6 5 6 6 6 5
 5 5 5 6 5 5 5 6 6 5 6 5 6 5 5 5 5 5 6 6 5 6 5 6 5 5 5 5 5 6 5 6 5 5 5 5 6
 6 5 6 5 5 6 5 5 6 6 5 5 6 5 5 5 6 6 6 5 5 6 7 5 5 6 5 5 5 6 5 6 6 5 6 5 5
 6 5 5 5 5 6 6 6 6 5 5 6 5 5 5 6 5 5 5 7 6 5 6 6 6 5 7 5 7 5 5 5 6 6 7 6 5
 6 5 6 6 5 5 6 5 6 5 5 5 5 7 6 6 5 5 5 6 6 6 5 5 5 6 5 6 5 5 6 6 5 6 6 6 5
 5 5 6 5 6 6 6 6 5 6 5 5 5 6 6 5 5 5 5 6 5 7 5 6 6 5 5 6 6 6 5 5 6 6 5 6 5
 5 7 5 5 6 6 6 6 5 5 6 5 5 5 5 5 5 6 6 6 5 6 6 6 5 5 6 5 6 6 5 6 6 6 6 5 5
 6 5 6 6 5 5 6 5 5 6 6 6 5 5 5 6 5 7 6 5 6 5 5 5 5 6 6 5 7 5 7 5 5 5 5 5]
confusion matrix
 [[  0   

In [46]:
w2 = DecisionTreeClassifier(criterion='gini',max_depth=9,min_samples_split=17)
model_perf(w2, x_train,x_test,y_test, y_train)

[6 6 5 5 5 5 6 5 6 6 6 7 6 6 5 5 6 6 5 5 5 6 5 5 7 6 5 6 7 5 5 5 5 5 6 5 5
 6 7 6 6 6 5 5 5 6 5 6 6 6 5 5 5 5 6 6 5 6 6 5 5 5 7 5 5 7 6 5 6 6 5 5 5 6
 5 6 4 6 5 6 6 6 5 5 6 6 6 5 7 7 5 7 7 5 7 7 7 5 7 5 7 5 5 6 7 6 6 7 5 7 6
 6 5 7 6 5 7 5 5 5 6 6 6 5 6 5 6 5 5 5 6 6 5 5 5 5 5 6 7 6 5 7 6 5 6 5 5 5
 5 5 5 5 6 5 7 5 6 6 5 5 5 5 6 5 5 6 4 6 6 6 7 5 6 5 6 6 5 6 6 7 7 6 7 5 6
 6 5 5 6 5 5 5 5 7 5 6 4 6 5 5 6 6 6 5 5 5 6 5 6 7 6 7 7 5 5 6 6 5 6 6 7 5
 6 5 6 6 6 6 7 6 5 5 7 5 6 5 5 5 5 5 6 6 5 5 5 6 6 6 6 5 6 6 5 5 6 5 5 5 6
 6 5 6 5 6 6 5 6 7 7 5 5 6 5 5 5 6 7 6 6 5 7 6 5 5 6 5 5 5 6 5 5 5 5 7 6 6
 6 5 5 6 5 6 7 5 6 5 5 7 5 5 6 7 5 5 5 7 5 5 5 6 6 7 7 5 6 5 6 5 6 6 6 6 7
 6 5 7 6 5 5 5 5 6 6 6 5 5 7 6 6 5 5 5 6 5 6 5 5 5 6 6 7 5 5 7 5 5 7 6 5 6
 5 5 7 5 7 6 6 6 5 7 5 5 5 6 5 5 5 6 5 5 5 7 6 5 6 7 5 6 7 7 5 6 7 6 5 7 5
 5 7 5 5 6 7 7 7 6 7 6 5 4 6 5 5 5 5 6 5 5 7 6 7 5 4 6 5 6 6 5 6 6 7 5 5 4
 7 5 5 7 6 5 6 5 5 6 6 5 5 5 5 6 5 7 6 5 6 5 5 5 4 6 7 7 6 6 6 5 4 5 5 5]
confusion matrix
 [[  0   